In [1]:
import tensorflow as tf
import gym
import numpy as np
import datetime

# from rl_agents.env_utils import rollouts_generator, get_adv_vtarg, get_gaeadv_vtarg
from rl_agents.vpg.agent import VPG_Agent
from rl_agents.ppo.agent import PPO_Agent
from rl_agents.training.buffers import GAE_Buffer
from rl_agents.training.sensei import Sensei, ExperimentRunner
from rl_agents.utils import get_actor_critic

# for auto-reloading external modules
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2

tf.random.set_seed(0)
tf.keras.backend.set_floatx('float64')

## Create GYM environment
Use Pendulum-v0 for now

In [2]:
# env_fn = lambda: gym.make('MountainCarContinuous-v0')
# env_fn = lambda: gym.make('Pendulum-v0')
# env_fn = lambda: gym.make('MountainCar-v0')
# env_fn = lambda: gym.make('CartPole-v0')
# env_fn = lambda: gym.make('LunarLanderContinuous-v2')
env_fn = lambda: gym.make('Acrobot-v1')
env = env_fn()
# continuous = check_if_continuous(env)
obs_dim = env.observation_space.shape
act_dim = env.action_space.shape or env.action_space.n

# Testing buffer

In [3]:
buff = GAE_Buffer(obs_dim, act_dim, 20, gamma=0.99, lam=0.95)

In [4]:
actor_vpg, critic_vpg = get_actor_critic(env)

In [5]:
jen_vpg = VPG_Agent(actor_vpg, critic_vpg, act_dim)

In [6]:
runner = ExperimentRunner(jen_vpg, env, buff)
runner.num_ite = 1

In [7]:
for i, rollout in enumerate(runner):
    print(i)

pi tf.Tensor([[0. 1. 0.]], shape=(1, 3), dtype=float64)
logp pi tf.Tensor([-1.22774607], shape=(1,), dtype=float64)
loc tf.Tensor([[0. 1. 0.]], shape=(1, 3), dtype=float64)
tf.Tensor(-1.2277460748173374, shape=(), dtype=float64)
pi tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float64)
logp pi tf.Tensor([-0.98976524], shape=(1,), dtype=float64)
loc tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float64)
tf.Tensor(-0.9897652422223007, shape=(), dtype=float64)
pi tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float64)
logp pi tf.Tensor([-1.09691269], shape=(1,), dtype=float64)
loc tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float64)
tf.Tensor(-1.0969126906313993, shape=(), dtype=float64)
pi tf.Tensor([[0. 0. 1.]], shape=(1, 3), dtype=float64)
logp pi tf.Tensor([-1.04099561], shape=(1,), dtype=float64)
loc tf.Tensor([[0. 0. 1.]], shape=(1, 3), dtype=float64)
tf.Tensor(-1.040995614534041, shape=(), dtype=float64)
pi tf.Tensor([[0. 0. 1.]], shape=(1, 3), dtype=float64)
logp pi tf.Tensor([-1.1326125

In [88]:
a = np.array([1,2,23,5,6])
a[slice(0,3)]

array([ 1,  2, 23])

In [9]:
actor_vpg, critic_vpg = get_actor_critic(env)
jen_vpg = VPG_Agent(actor_vpg, critic_vpg, is_continuous, act_dim)

buff = GAE_Buffer(obs_dim, act_dim, 20, gamma=0.99, lam=0.95)
runner = ExperimentRunner(jen_vpg, env, buff)
runner.num_ite = 2

NameError: name 'gym' is not defined

# Vanilla Policy Gradient

## Initialization

In [88]:
actor_vpg = GaussianActor(obs_dim, act_dim) if is_continuous else CategoricalActor(obs_dim, act_dim)
critic_vpg = Critic(obs_dim)
jen_vpg = VPG_Agent(actor_vpg, critic_vpg, is_continuous, act_dim)
generator_vpg = rollouts_generator(jen_vpg, env, is_continuous, horizon=2048)

alg_name = "VPG"
lam = 0.95
gamma = 0.99
epochs_actor = 1
epochs_critic = 40
sensei_vpg = Sensei(jen_vpg, alg_name, env_fn,
                    horizon=2048, epochs_actor=epochs_actor, epochs_critic=epochs_critic,
                    gamma=gamma, gae_lambda=lam,
                    log_dir='logs')

# Training loop

In [85]:
num_ite = 100
sensei_vpg.train(num_ite, batch_size=256)

In [94]:
num_ite = 50
sensei_vpg.train(num_ite, record=False, batch_size=256)

[-14.76764555 -14.74228885 -14.72495464 -14.71601001 -14.6916882
 -14.68221407 -14.6736526  -14.66602628 -14.64543579 -14.63120373
 -14.61112949 -14.60284017 -14.5955779  -14.57792352 -14.56018016
 -14.55268418 -14.5461986  -14.53556891 -14.53033664 -14.52105083
 -14.51715561 -14.50416203 -14.50083429 -14.48844766 -14.47561756
 -14.46728064 -14.46433129 -14.45228882 -14.4501251  -14.4386215
 -14.43739599 -14.43209848 -14.42148894 -14.41022144 -14.41014619
 -14.41198928 -14.40928233 -14.41419128 -14.41420922 -14.41498523
 -14.41650307 -14.41872627 -14.42159498 -14.43427695 -14.44999623
 -14.45837914 -14.47819717 -14.50126613 -14.52766477 -14.53080078
 -14.53052769 -14.53994178 -14.54783524 -14.53953655 -14.52630285
 -14.53638831 -14.51708832 -14.52107161 -14.50944957 -14.49412983
 -14.47496115 -14.43762258 -14.4083559  -14.3617842  -14.32278637
 -14.26772205 -14.21967405 -14.15699411 -14.10067782 -14.04110273
 -13.97830722 -13.91230173 -13.8345347  -13.7691723  -13.69330775
 -13.6139403

tf.Tensor(
[-14.39486152 -14.39723198 -14.39970354 -14.40225552 -14.40486696
 -14.40751685 -14.4190138  -14.42248014 -14.41718173 -14.4108062
 -14.42111448 -14.43196949 -14.42658383 -14.42865348 -14.43059178
 -14.43238644 -14.44226269 -14.45248841 -14.46293747 -14.47349002
 -14.47684712 -14.4868459  -14.48987897 -14.49236919 -14.49431379
 -14.50243232 -14.50391316 -14.4981446  -14.49778863 -14.49003196
 -14.48785481 -14.49213152 -14.49655407 -14.50108164 -14.49904474
 -14.48958089 -14.49258715 -14.48889739 -14.47751018 -14.46441776
 -14.4649927  -14.45839519 -14.45911304 -14.45256648 -14.44559342
 -14.43822365 -14.4304921  -14.4309351  -14.43213414 -14.42565334
 -14.41894497 -14.41205118 -14.4139498  -14.39881633 -14.40086788
 -14.3853594  -14.38777532 -14.39137497 -14.3867063  -14.38217806
 -14.37783116 -14.37370609 -14.36984246 -14.36627833 -14.36304972
 -14.37025092 -14.36885909 -14.37768378 -14.37798749 -14.36870731
 -14.3685612  -14.36876353 -14.35922129 -14.36919717 -14.37050446


[-14.24745078 -14.24004641 -14.225919   -14.224625   -14.21767717
 -14.20454172 -14.2034006  -14.19704698 -14.19090841 -14.17903091
 -14.17841875 -14.17896706 -14.18076907 -14.17760887 -14.16855255
 -14.16503459 -14.15571413 -14.15183393 -14.15441515 -14.15210471
 -14.15013473 -14.14204865 -14.14628452 -14.15228055 -14.14590301
 -14.15303322 -14.16223498 -14.16563314 -14.16953957 -14.17393044
 -14.1787721  -14.19318853 -14.19100546 -14.1969181  -14.2030281
 -14.21957368 -14.23858716 -14.23737269 -14.24528236 -14.25287007
 -14.27202589 -14.28060883 -14.30130964 -14.29740037 -14.31657814
 -14.33722868 -14.35930692 -14.36799762 -14.36068795 -14.37827543
 -14.3818687  -14.38362907 -14.39798593 -14.39805202 -14.4106589
 -14.39476411 -14.4032008  -14.41176269 -14.40657417 -14.38670158
 -14.38961172 -14.38016282 -14.36961925 -14.36970863 -14.35872778
 -14.34704615 -14.32467251 -14.3016287  -14.2958149  -14.28197525
 -14.26011704 -14.23821527 -14.23032003 -14.21637935 -14.19634663
 -14.1884177

tf.Tensor(
[-16.70895514 -16.70644333 -16.70407186 -16.70186584 -16.70532174
 -16.69858797 -16.69123346 -16.69505757 -16.6996563  -16.6937796
 -16.68738127 -16.69244498 -16.69825425 -16.69351261 -16.68832255
 -16.6945356  -16.6900007  -16.6909939  -16.69801125 -16.70009657
 -16.70778987 -16.71583727 -16.71922075 -16.71767903 -16.7254981
 -16.72884737 -16.73211967 -16.73077568 -16.72891928 -16.73569575
 -16.73826621 -16.73637752 -16.74263687 -16.74064869 -16.74653484
 -16.75245083 -16.75832714 -16.76050281 -16.76242802 -16.76758861
 -16.76928545 -16.77069894 -16.76847691 -16.77236779 -16.76964986
 -16.76966159 -16.76941491 -16.76891051 -16.76468478 -16.76680428
 -16.76555567 -16.76753784 -16.76264463 -16.76420911 -16.76588354
 -16.76765044 -16.76607106 -16.7642283  -16.76212374 -16.76337176
 -16.75749494 -16.75460139 -16.75532418 -16.75625191 -16.74965173
 -16.75028485 -16.74717351 -16.73962466 -16.73557496 -16.72672406
 -16.716811   -16.70577557 -16.69356172 -16.69208917 -16.67949452
 

[-11.13306787 -10.95451723 -10.76099822 -10.55899444 -10.34115462
 -10.10996549  -9.87028812  -9.61588571  -9.34303946  -9.05325437
  -8.74545984  -8.41851422  -8.07120099  -7.70222469  -7.31020658
  -6.8936798   -6.45108434  -5.98076151  -5.48094799  -4.94788093
  -4.3812896   -3.78077857  -3.14253316  -2.46591099  -1.74512534
  -0.98079939  -0.1667054    0.69866235   1.6185456    2.59434907
   3.63344611   4.73578128   5.90714142   7.1518161    8.47721349
   9.8831666   11.37706024  12.96435909  14.6587262   16.45678629
 -13.91561059 -13.91863407 -13.91694951 -13.91970164 -13.91790699
 -13.91132219 -13.90847058 -13.90146677 -13.89424687 -13.89030851
 -13.8864084  -13.88572128 -13.88228876 -13.87894052 -13.87569368
 -13.86995521 -13.86916751 -13.86876417 -13.86630136 -13.86396424
 -13.85952721 -13.85718859 -13.85295576 -13.85064813 -13.8484803
 -13.84645009 -13.84455612 -13.8446374  -13.84327742 -13.84023376
 -13.83712336 -13.83394574 -13.83069891 -13.82900446 -13.82913692
 -13.826278

tf.Tensor(
[-18.91353818 -18.91935425 -18.92513386 -18.93078277 -18.9340464
 -18.93499384 -18.93984306 -18.94257925 -18.94511546 -18.94744948
 -18.94958156 -18.95307903 -18.95339884 -18.95342789 -18.95316806
 -18.95561297 -18.95510635 -18.95576764 -18.95628364 -18.95803972
 -18.95839263 -18.95991437 -18.96009546 -18.96012637 -18.96127481
 -18.9611359  -18.95956399 -18.95897788 -18.95823718 -18.95593642
 -18.9561435  -18.954926   -18.95354011 -18.9519816  -18.95024643
 -18.94833107 -18.94623276 -18.94207199 -18.93932211 -18.93422878
 -18.92840828 -18.92687156 -18.92560181 -18.92462669 -18.92136162
 -18.91803615 -18.9146819  -18.91429892 -18.9114139  -18.9116749
 -18.90939454 -18.90402917 -18.89822212 -18.89197627 -18.88530207
 -18.886388   -18.88831973 -18.88321736 -18.88611286 -18.88589348
 -18.88612535 -18.88280214 -18.88354833 -18.8806837  -18.88602582
 -18.88418286 -18.88636658 -18.88894457 -18.88805186 -18.89100917
 -18.89054085 -18.89006112 -18.89696415 -18.90071595 -18.90460582
 

[-13.38315881 -13.37477622 -13.36581519 -13.35856998 -13.34868275
 -13.34286274 -13.33471902 -13.32623706 -13.32009179 -13.31135968
 -13.29934766 -13.28925662 -13.28175636 -13.27453983 -13.2676852
 -13.26127641 -13.25117551 -13.24045044 -13.22454068 -13.21138241
 -13.19258832 -13.1718299  -13.15828815 -13.14444967 -13.12494114
 -13.10375764 -13.08074108 -13.05027514 -13.01691099 -12.98570828
 -12.94695118 -12.90508938 -12.86471493 -12.81697354 -12.76594948
 -12.71558694 -12.66602489 -12.61358996 -12.55402642 -12.49066052
 -12.41958067 -12.34753774 -12.27104869 -12.19319566 -12.10741116
 -12.01632598 -11.91657477 -11.81070428 -11.70378064 -11.58507819
 -11.45910585 -11.32776371 -11.18838171 -11.04044506 -10.88340579
 -10.71668107 -10.5375979  -10.35134842 -10.14969873  -9.93932934
  -9.71610622  -9.47923829  -9.22789164  -8.95660727  -8.67264634
  -8.36654022  -8.0433334   -7.70231981  -7.33524045  -6.94994228
  -6.53817636  -6.1034257   -5.63883783  -5.14826585  -4.62400883
  -4.063170

tf.Tensor(
[-21.05727175 -21.05622059 -21.0551209  -21.05303311 -21.05169738
 -21.0492402  -21.04767841 -21.04733497 -21.04721841 -21.04485132
 -21.04362036 -21.04247409 -21.04143283 -21.03902122 -21.03957211
 -21.03740678 -21.03677194 -21.03633562 -21.03610727 -21.03441706
 -21.03442982 -21.03294291 -21.0314444  -21.03179906 -21.03058857
 -21.03307438 -21.03585847 -21.03729238 -21.04035873 -21.04213371
 -21.04395709 -21.04453351 -21.04506044 -21.04553629 -21.04595971
 -21.04867511 -21.05134135 -21.0520046  -21.054437   -21.05593096
 -21.05733515 -21.05790356 -21.05836021 -21.05942048 -21.06040588
 -21.06192618 -21.06221775 -21.06240005 -21.0614404  -21.06054576
 -21.05948927 -21.0582561  -21.05762633 -21.05697108 -21.05629438
 -21.05560086 -21.05398882 -21.05408165 -21.05240808 -21.05257023
 -21.05189595 -21.05124721 -21.04955252 -21.04993574 -21.04941727
 -21.04895633 -21.04739672 -21.04810237 -21.04785893 -21.04649848
 -21.04748159 -21.04865097 -21.04772491 -21.0467082  -21.04801483

tf.Tensor(
[-21.74647827 -21.74687069 -21.74647433 -21.74685931 -21.74645522
 -21.74599519 -21.74547939 -21.74578714 -21.74613951 -21.74479847
 -21.74323114 -21.74242574 -21.7405232  -21.74055367 -21.74068805
 -21.73873734 -21.73886664 -21.73797407 -21.73824043 -21.73747014
 -21.7366903  -21.73713311 -21.73651032 -21.73712083 -21.73541909
 -21.73482278 -21.73424822 -21.73370134 -21.73180135 -21.73257118
 -21.73072237 -21.73018598 -21.73118606 -21.73237899 -21.73236766
 -21.73098932 -21.73093938 -21.73238023 -21.73396647 -21.73436984
 -21.73347848 -21.73513379 -21.73687461 -21.7374939  -21.73925992
 -21.73884056 -21.7382876  -21.73876492 -21.73923559 -21.74078254
 -21.74132006 -21.74182958 -21.74230856 -21.74372349 -21.74326557
 -21.74363164 -21.74396003 -21.74330378 -21.74440638 -21.74462511
 -21.74480371 -21.74494182 -21.74591805 -21.74689932 -21.74707236
 -21.74719277 -21.74643614 -21.74550891 -21.74439896 -21.74404147
 -21.74364374 -21.74415229 -21.74379156 -21.74241684 -21.74285584

[-12.98586422 -12.98109482 -12.97600677 -12.97211235 -12.96808077
 -12.96236038 -12.95483682 -12.94957692 -12.94271853 -12.93545373
 -12.92776597 -12.91963642 -12.90988364 -12.90066785 -12.89094608
 -12.8806886  -12.86986283 -12.85843334 -12.8463618  -12.83360696
 -12.82101312 -12.80600285 -12.79177248 -12.7768036  -12.7592825
 -12.74236723 -12.72366119 -12.70382921 -12.68193635 -12.65866268
 -12.63472849 -12.60934418 -12.58325735 -12.55483202 -12.52556798
 -12.49467389 -12.46206775 -12.4254987  -12.38759113 -12.34733375
 -12.30344883 -12.25896778 -12.21070001 -12.15816475 -12.10341072
 -12.04653287 -11.98634142 -11.92264776 -11.85357734 -11.78010172
 -11.70018854 -11.61665184 -11.52957775 -11.43725043 -11.33722613
 -11.23070535 -11.11512493 -10.99606912 -10.86963192 -10.73292299
 -10.58972425 -10.43499933 -10.27273477 -10.09756338  -9.91363252
  -9.71806076  -9.50720801  -9.27988325  -9.04032712  -8.7853202
  -8.5115122   -8.22245827  -7.91500144  -7.58600848  -7.23811815
  -6.8665549

tf.Tensor(
[-23.75141999 -23.75219991 -23.75383566 -23.75468915 -23.75552626
 -23.75634001 -23.75712453 -23.75787502 -23.75858768 -23.75983588
 -23.76102259 -23.76166194 -23.76269488 -23.7628158  -23.76327946
 -23.76327974 -23.76361012 -23.76428165 -23.76418005 -23.76399218
 -23.76371408 -23.76414656 -23.76419135 -23.76419851 -23.76454626
 -23.76488606 -23.76486602 -23.76480619 -23.76433334 -23.76374526
 -23.76302819 -23.7621656  -23.76164562 -23.76054081 -23.7592387
 -23.75898789 -23.75879309 -23.7573549  -23.755687   -23.75457982
 -23.75342742 -23.75312077 -23.75294687 -23.75202108 -23.75110199
 -23.75020131 -23.74828317 -23.74730006 -23.74750698 -23.74682115
 -23.74503458 -23.74310448 -23.74103306 -23.74027945 -23.73969091
 -23.73928095 -23.75478013 -23.75496525 -23.75516839 -23.7553874
 -23.75485525 -23.7550256  -23.75521375 -23.75615851 -23.75644517
 -23.75673473 -23.7563222  -23.75654572 -23.75605924 -23.75548139
 -23.75557597 -23.75641493 -23.75588791 -23.75601552 -23.75615342
 

[-12.7062369  -12.704943   -12.70506544 -12.7051568  -12.70355971
 -12.70334293 -12.70150175 -12.70098532 -12.70042502 -12.70137694
 -12.70093367 -12.70044076 -12.70151044 -12.70281947 -12.70261898
 -12.70412866 -12.70404951 -12.70576504 -12.70776472 -12.70799998
 -12.71021896 -12.70846405 -12.70639101 -12.70593209 -12.7053601
 -12.70661835 -12.70606689 -12.70738429 -12.7068429  -12.70617142
 -12.70345163 -12.70417331 -12.7031235  -12.7001463  -12.69865489
 -12.69542521 -12.69356304 -12.69015208 -12.68798205 -12.68574429
 -12.6821804  -12.68089412 -12.67728103 -12.67577764 -12.67318498
 -12.67162279 -12.66788585 -12.66608419 -12.66218385 -12.65909484
 -12.65491209 -12.65053891 -12.64773281 -12.64491197 -12.64018742
 -12.63702016 -12.63193368 -12.62744893 -12.62274773 -12.61781572
 -12.61263786 -12.60719835 -12.60148057 -12.59448842 -12.58900452
 -12.58341379 -12.57657727 -12.57057916 -12.56194717 -12.55269032
 -12.54401436 -12.53484406 -12.52380361 -12.51468656 -12.50380416
 -12.490763

tf.Tensor(
[-25.6289592  -25.62073384 -25.61170938 -25.60187373 -25.59756936
 -25.58717298 -25.58324087 -25.57268707 -25.57704506 -25.56787621
 -25.56660034 -25.57399741 -25.56758629 -25.56131644 -25.55527063
 -25.54953365 -25.54419013 -25.54842777 -25.54495545 -25.55952507
 -25.57441074 -25.57501512 -25.59004006 -25.59846441 -25.60689319
 -25.61519533 -25.61818869 -25.62601869 -25.62898993 -25.63617742
 -25.64296927 -25.64564383 -25.65162314 -25.65390033 -25.65906629
 -25.6638174  -25.66546635 -25.6668237  -25.67046102 -25.67603981
 -25.68102195 -25.68543532 -25.68771037 -25.69118316 -25.69421706
 -25.69562211 -25.69554431 -25.69762265 -25.69942876 -25.70098828
 -25.70038236 -25.69952599 -25.69840456 -25.69812095 -25.69767318
 -25.69589341 -25.69374975 -25.69386333 -25.69260187 -25.69113121
 -25.68792564 -25.68411703 -25.67959385 -25.67840104 -25.67287567
 -25.66631861 -25.66142872 -25.65903572 -25.65357265 -25.65103214
 -25.64508853 -25.63868082 -25.63182983 -25.61973996 -25.61665113

[  2.67304157   3.6101939    4.60456329   5.66914083   6.81050549
   8.00500583   9.27284027  10.61855455  12.06136399  13.58105104
  15.19482337  16.94490824  18.80867494  20.75859602  22.83133059
  25.05560872 -12.41478424 -12.41352126 -12.40461111 -12.40250672
 -12.40034527 -12.39147174 -12.38873768 -12.3799891  -12.38273729
 -12.38011805 -12.38349614 -12.37562997 -12.3731789  -12.3764596
 -12.36906005 -12.3668358  -12.37016553 -12.37434442 -12.37344856
 -12.37264441 -12.37193607 -12.37735007 -12.37747416 -12.37770359
 -12.38451192 -12.38566783 -12.38031495 -12.37461355 -12.38104727
 -12.38189711 -12.37633264 -12.37042676 -12.36421936 -12.35774594
 -12.35646312 -12.36101648 -12.36054451 -12.36017501 -12.35990794
 -12.3537391  -12.35299769 -12.34650944 -12.35119495 -12.34473959
 -12.34974422 -12.34945706 -12.34924964 -12.34271142 -12.34188194
 -12.34771547 -12.3477551  -12.35508935 -12.35606823 -12.35704995
 -12.36618796 -12.37692764 -12.37985594 -12.38264798 -12.38524497
 -12.377977

tf.Tensor(
[-27.55049952 -27.51990609 -27.48590816 -27.4984108  -27.51104762
 -27.47687636 -27.49037763 -27.50402908 -27.51768685 -27.50898001
 -27.5228054  -27.53644402 -27.52870305 -27.5206191  -27.48880544
 -27.47929867 -27.44364745 -27.43317236 -27.39394847 -27.3831892
 -27.34096792 -27.3637517  -27.32262838 -27.34901385 -27.34400905
 -27.34038043 -27.30356016 -27.30223124 -27.30274841 -27.33971384
 -27.37644231 -27.38239372 -27.35781829 -27.36561369 -27.37448952
 -27.38432281 -27.39498189 -27.40632956 -27.38850216 -27.37029917
 -27.35186217 -27.33334866 -27.34912505 -27.36578639 -27.38310462
 -27.4008578  -27.41883456 -27.4082132  -27.39747564 -27.41663222
 -27.46273111 -27.45505631 -27.44703368 -27.43870764 -27.43012733
 -27.47537614 -27.46831871 -27.48631755 -27.5265907  -27.54255414
 -27.53664736 -27.55124138 -27.56491989 -27.59609335 -27.62405749
 -27.61784333 -27.61039767 -27.634622   -27.62618428 -27.64755032
 -27.65273004 -27.64241719 -27.65999022 -27.67571458 -27.67725172


[-11.77125979 -11.741301   -11.75544679 -11.765082   -11.76883355
 -11.82913991 -11.82352603 -11.87808017 -11.78709753 -11.68436217
 -11.63152096 -11.56824246 -11.43926964 -11.30505734 -11.210916
 -11.15332945 -11.08932783 -11.01858023 -10.89761285 -10.80963804
 -10.63880826 -10.46729249 -10.32128178 -10.16928211 -10.01104638
  -9.86685498  -9.71435336  -9.53389268  -9.34516861  -9.16309517
  -8.95550749  -8.72474517  -8.48486625  -8.25363616  -7.9903175
  -7.71413932  -7.42375157  -7.12979917  -6.806236    -6.47497127
  -6.11813656  -5.74507819  -5.34942321  -4.92398355  -4.4670104
  -3.99270119  -3.48964643  -2.95618576  -2.38366905  -1.78290703
  -1.13819626  -0.45360093   0.27334613   1.04525918   1.87428243
   2.74595994   3.66080489   4.65359107   5.69719327   6.81804372
   7.98288749   9.21619378  10.55759755  11.96627352  13.44142136
  15.00246626  16.65392168  18.43353564  20.28869898  22.33162373
  24.46870218  26.69706255 -12.04325191 -12.0602697  -12.080057
 -12.08168149 -1

tf.Tensor(
[-29.54464864 -29.5196252  -29.50644985 -29.4736404  -29.47410864
 -29.43438774 -29.41102463 -29.38506037 -29.35635606 -29.32479168
 -29.25759625 -29.1790262  -29.08773164 -28.98243877 -28.97853493
 -28.97778346 -28.92412596 -28.9299953  -28.81663103 -28.76394607
 -28.63730328 -28.50069235 -28.54133195 -28.41132076 -29.242407
 -29.23506541 -29.26317036 -29.28983935 -29.31495608 -29.36610903
 -29.36037751 -29.38030156 -29.39855868 -29.41517066 -29.43017239
 -29.44360791 -29.43477775 -29.42450299 -29.43502219 -29.42271293
 -29.45225596 -29.47821167 -29.48364502 -29.48786565 -29.47293256
 -29.47491457 -29.47580408 -29.49335482 -29.50876133 -29.4899158
 -29.4680908  -29.48153015 -29.47571047 -29.46867473 -29.47911845
 -29.48826754 -29.46002521 -29.44821806 -29.45539255 -29.44163466
 -29.4036344  -29.38526882 -29.3905152  -29.34351266 -29.28924657
 -29.22693338 -29.15582378 -29.07525556 -29.08505836 -28.99827126
 -28.90194756 -28.86148925 -28.82332591 -28.85425062 -28.82552749
 -

[-1.14393868e+01 -1.14821546e+01 -1.14882386e+01 -1.14963712e+01
 -1.15066198e+01 -1.15730773e+01 -1.15932778e+01 -1.16157014e+01
 -1.16402479e+01 -1.17356849e+01 -1.17709913e+01 -1.18880307e+01
 -1.18503306e+01 -1.18082699e+01 -1.19216793e+01 -1.18746842e+01
 -1.19915730e+01 -1.20274958e+01 -1.19706360e+01 -1.19095567e+01
 -1.20121570e+01 -1.19446063e+01 -1.20433249e+01 -1.20571244e+01
 -1.21619059e+01 -1.20799140e+01 -1.20826297e+01 -1.21737818e+01
 -1.20826585e+01 -1.20742495e+01 -1.19815910e+01 -1.18905895e+01
 -1.18020066e+01 -1.17758891e+01 -1.17486946e+01 -1.17807581e+01
 -1.16952474e+01 -1.16653634e+01 -1.16348560e+01 -1.16567925e+01
 -1.16268644e+01 -1.16500256e+01 -1.16768329e+01 -1.16484677e+01
 -1.15658358e+01 -1.15337635e+01 -1.14541626e+01 -1.14191235e+01
 -1.13835669e+01 -1.13910506e+01 -1.13133752e+01 -1.12368541e+01
 -1.12353090e+01 -1.12373540e+01 -1.11998014e+01 -1.11612661e+01
 -1.11216735e+01 -1.10409101e+01 -1.09593334e+01 -1.08766994e+01
 -1.08599445e+01 -1.08093

[-10.87619622 -10.91046286 -11.05079342 -11.22620781 -11.304798
 -11.53209833 -11.47974933 -11.41431853 -11.33591469 -11.24485613
 -11.1416373  -11.29988728 -11.47866682 -11.50165599 -11.51223404
 -11.6883158  -11.67871623 -11.84459192 -11.61288268 -11.73388168
 -11.65196347 -11.74136764 -11.62179752 -11.67230391 -11.51517286
 -11.17279191 -11.14459011 -11.10285408 -10.7444729  -10.66065631
 -10.43288798 -10.19990124 -10.07042015  -9.82434795  -9.66928613
  -9.32659732  -9.14518635  -8.81193247  -8.60530189  -8.32870511
  -8.09709504  -7.85268506  -7.5452818   -7.27150098  -6.98239061
  -6.63436714  -6.23587613  -5.82799643  -5.40742714  -4.97106166
  -4.53439513  -4.09231896  -3.6053421   -3.07340339  -2.52835363
  -1.95123124  -1.32510723  -0.66292401   0.03809899   0.7554631
   1.52893087   2.36338323   3.21888082   4.15675369   5.15190551
   6.20801303   7.32894744   8.48179125   9.72007838  11.05552485
  12.44730566  13.88796878  15.43924637  17.0785926   18.75754571
  20.50968991

tf.Tensor(
[-32.15816599 -32.10404305 -32.13227532 -32.15583129 -32.09175872
 -32.0657174  -32.08362997 -32.05111024 -32.01379137 -32.02469809
 -31.97986121 -31.98591437 -31.87104911 -31.80665037 -31.65579319
 -31.4770979  -31.26716903 -31.02288464 -31.03573721 -31.05170985
 -30.93259871 -30.64954485 -30.33112448 -30.19145672 -30.26522782
 -29.92978273 -29.56908466 -29.71730719 -29.37450749 -29.57696742
 -29.78784085 -30.00239358 -31.52575911 -31.61013312 -31.60247749
 -31.50134184 -31.39107646 -31.38375832 -31.48073675 -31.37116556
 -31.47070942 -31.56227223 -31.64585462 -31.55142902 -31.54563836
 -31.44185429 -31.32950351 -31.43350585 -31.52935814 -31.61700813
 -31.52161458 -31.60932359 -31.51266289 -31.60063994 -31.50274666
 -31.59119643 -31.49214272 -31.5812603  -31.57576225 -31.56990672
 -31.56373241 -31.64556595 -31.63829036 -31.54053824 -31.5321308
 -31.61470491 -31.60573999 -31.68117715 -31.58479329 -31.47871627
 -31.36291584 -31.35225619 -31.34295482 -31.21890704 -31.21361454


tf.Tensor(
[-31.31870146 -31.18723606 -31.23169533 -31.2828687  -31.49249517
 -31.68333434 -31.85515231 -31.78635675 -31.94979018 -31.99608602
 -32.04104886 -31.98514628 -31.92734309 -32.07705017 -32.02445802
 -31.96987318 -31.91367829 -31.85632536 -31.79833449 -31.96983643
 -32.02422145 -32.07636024 -32.03047646 -32.08261646 -32.21911268
 -32.33716678 -32.29912239 -32.33420579 -32.36612611 -32.45960693
 -32.53972807 -32.50148372 -32.4583727  -32.41011953 -32.35646916
 -32.43672498 -32.44637498 -32.38843422 -32.32382581 -32.39887741
 -32.46493984 -32.40002067 -32.46148755 -32.51544621 -32.44756872
 -32.49764334 -32.42261309 -32.33696351 -32.31714425 -32.2950847
 -32.3455478  -32.32039003 -32.36554727 -32.2614542  -32.14273106
 -32.10482329 -32.06513787 -32.11912305 -32.07893175 -31.93437427
 -31.99488359 -32.05238872 -32.10663499 -32.15744096 -32.20468999
 -32.07379502 -32.12369352 -31.98112899 -31.82044279 -31.88415463
 -31.83477922 -31.6600709  -31.46720497 -31.56031668 -31.51465185


[-10.02478672  -9.98528096  -9.90536941  -9.91563995  -9.88962485
  -9.87031423  -9.8590458   -9.85726606  -9.78261664  -9.70500118
  -9.80812366  -9.8443537   -9.89688866  -9.96706737 -10.05592125
 -10.16404851 -10.49781712 -10.67393268 -10.61845646 -11.0651286
 -10.9916944  -11.18290174 -11.06753889 -10.92546421 -11.04509872
 -11.4817577  -11.60103803 -11.34720196 -11.74735103 -12.17493062
 -12.62046387 -12.18734543 -12.11680845 -11.63205656 -11.47414058
 -11.62515012 -11.75686273 -11.16757339 -10.89055037 -10.88071169
 -10.55937091 -10.48793027 -10.3936003  -10.0188942   -9.64063137
  -9.26144578  -8.88287485  -8.36132638  -7.99546148  -7.52812881
  -7.08648053  -6.79509003  -6.48806797  -6.03893621  -5.59411899
  -5.2282004   -4.76217063  -4.31705602  -3.85028886  -3.35962781
  -2.81895975  -2.29652795  -1.69957291  -1.09064172  -0.44612666
   0.21706674   0.93938058   1.68327573   2.51481207   3.3950051
   4.30790949   5.2961652    6.30161805   7.41188462   8.58965974
   9.8150828

tf.Tensor(
[-34.48262488 -34.4787847  -34.45565581 -34.44635151 -34.41294167
 -34.39613094 -34.37545239 -34.31991092 -34.28682628 -34.28514526
 -34.28089415 -34.19227437 -34.18181685 -34.06259326 -33.9807726
 -33.95884263 -33.85863026 -33.742738   -33.49865783 -33.33212329
 -32.98466258 -32.75687423 -32.50815862 -31.98640416 -31.36659144
 -31.01908949 -30.26287619 -29.89577769 -29.55334917 -29.74472261
 -29.98164763 -29.8043606  -29.16948628 -29.60859471 -29.08071813
 -29.13705959 -29.2598709  -28.90949339 -28.61290408 -29.49531935
 -33.68195656 -33.74373814 -33.60851949 -33.57048071 -33.64079633
 -33.70651857 -33.56741744 -33.53000994 -33.36786749 -33.45726645
 -33.54185262 -33.62117157 -33.47801318 -33.4471707  -33.28458875
 -33.10466268 -33.23103668 -33.35054736 -33.33399259 -33.17667361
 -33.31157058 -33.30560921 -33.30309815 -33.15840302 -33.00415354
 -32.84187459 -32.86651615 -32.70950981 -32.75528264 -32.98939778
 -33.20049803 -33.38846901 -33.43519422 -33.59647539 -33.52819783


[-11.86217018 -12.02579333 -12.19116278 -11.91989467 -11.85284799
 -11.78181295 -11.70834708 -11.63385014 -11.42654063 -11.24767517
 -11.28878402 -11.22567732 -11.26292781 -11.2013391  -11.23540167
 -11.09034211 -11.11657883 -11.14505012 -11.01628057 -10.90571151
 -10.92164652 -10.94062489 -10.89895173 -10.91954149 -10.8806769
 -10.78998281 -10.75548084 -10.72248689 -10.69085798 -10.66047346
 -10.59097022 -10.60183327 -10.6186569  -10.55050469 -10.48624407
 -10.46069718 -10.47689266 -10.45613107 -10.39396911 -10.37362019
 -10.4021599  -10.38997206 -10.38061961 -10.31911096 -10.31135267
 -10.25038229 -10.18944557 -10.24309253 -10.24867315 -10.26060785
 -10.20138768 -10.30432088 -10.34022    -10.28264513 -10.43711382
 -10.50250379 -10.57802396 -10.66350745 -10.93200575 -11.05410838
 -11.18304947 -11.10409502 -11.44706369 -11.58500422 -11.47135306
 -11.58303903 -11.95716255 -11.79414717 -11.62234684 -11.68101544
 -11.4888218  -11.29538525 -11.10313881 -10.91392073 -11.0656836
 -11.0371787

tf.Tensor(
[-35.12269578 -35.15176135 -35.17992799 -35.29117777 -35.38339984
 -35.39718504 -35.34035877 -35.27885309 -35.29641442 -35.31265794
 -35.39786477 -35.33821959 -35.27331993 -35.28793488 -35.30142318
 -35.31374251 -35.32485905 -35.25631032 -35.34618376 -35.35403803
 -35.36058624 -35.43168854 -35.43274872 -35.36642861 -35.36672278
 -35.36572764 -35.36344397 -35.35987392 -35.42203753 -35.34607152
 -35.33810954 -35.24992886 -35.24148614 -35.31335545 -35.3747812
 -35.36070506 -35.41306201 -35.39508486 -35.37502204 -35.41996419
 -35.32562603 -35.29856376 -35.3459549  -35.23482722 -35.10589256
 -34.95819204 -34.92158867 -35.00551119 -34.84617363 -34.66850001
 -34.47375596 -34.62020588 -34.43119547 -34.4227707  -34.59314775
 -34.59285617 -34.42718143 -34.4459388  -34.4716304  -34.50372554
 -34.36321499 -34.59063866 -34.47200663 -34.35637783 -34.60903113
 -34.82287157 -34.88089578 -34.80890621 -34.99885858 -35.15561304
 -35.19891773 -35.32021425 -35.27463461 -35.22757377 -35.17956003


[-1.06130127e+01 -1.05373328e+01 -1.04628398e+01 -1.06648551e+01
 -1.05826957e+01 -1.08153193e+01 -1.08982200e+01 -1.07978142e+01
 -1.08727414e+01 -1.09490967e+01 -1.12405789e+01 -1.15755887e+01
 -1.14097186e+01 -1.14815367e+01 -1.18106996e+01 -1.18697629e+01
 -1.16478865e+01 -1.19426087e+01 -1.16978015e+01 -1.17020407e+01
 -1.16951151e+01 -1.16776787e+01 -1.14405217e+01 -1.14099649e+01
 -1.13736196e+01 -1.15179651e+01 -1.14662167e+01 -1.15973592e+01
 -1.13557068e+01 -1.14587826e+01 -1.13894970e+01 -1.11806654e+01
 -1.11215393e+01 -1.10644685e+01 -1.10098296e+01 -1.09578652e+01
 -1.08254917e+01 -1.08611660e+01 -1.08989496e+01 -1.07786138e+01
 -1.07402175e+01 -1.06467754e+01 -1.05678621e+01 -1.05854630e+01
 -1.05577980e+01 -1.05785690e+01 -1.06037492e+01 -1.05778991e+01
 -1.05533329e+01 -1.04837981e+01 -1.05072694e+01 -1.04864274e+01
 -1.05167205e+01 -1.05545271e+01 -1.06006218e+01 -1.05849834e+01
 -1.06405320e+01 -1.06272428e+01 -1.05454577e+01 -1.06024031e+01
 -1.05920303e+01 -1.05128

[-10.5738414  -10.49501875 -10.4232696  -10.42188197 -10.49819058
 -10.59253318 -10.60287124 -10.52095487 -10.53021217 -10.64060516
 -10.55485243 -10.47568665 -10.48676395 -10.49992017 -10.42373958
 -10.43643704 -10.36370276 -10.46926306 -10.39339829 -10.51430025
 -10.6640436  -10.84492037 -11.05831364 -11.30438503 -11.35634095
 -11.40248539 -11.24000982 -11.09118235 -11.29437204 -11.13620995
 -10.99356135 -10.86527888 -10.87185408 -10.75532483 -10.75786998
 -10.88191897 -10.76265068 -10.76257188 -10.76178532 -10.76027289
 -10.65225605 -10.64837523 -10.64440519 -10.74646985 -10.74322575
 -10.73917766 -10.62964036 -10.72786953 -10.72206116 -10.61206333
 -10.51330898 -10.59507791 -10.49610509 -10.48682102 -10.57015741
 -10.66826748 -10.66176156 -10.6542506  -10.64570054 -10.53192794
 -10.42878849 -10.33454632 -10.40166703 -10.3060531  -10.29133275
 -10.27694524 -10.26287803 -10.17047756 -10.23518636 -10.22258254
 -10.30727438 -10.29826552 -10.28865558 -10.27825901 -10.38705948
 -10.37759

tf.Tensor(
[-37.32419392 -37.25427672 -37.26439663 -37.34721973 -37.27800052
 -37.28507399 -37.20929875 -37.12728181 -37.23475449 -37.24489308
 -37.33040544 -37.25877289 -37.18043741 -37.09609387 -37.00684285
 -37.03487854 -37.06305282 -36.97876007 -37.0165797  -37.05397206
 -36.97803087 -37.02484486 -37.17081768 -37.20412779 -37.144761
 -37.08474448 -37.13189322 -37.07650923 -37.0226438  -36.97161788
 -37.14898491 -37.20341186 -37.16491257 -37.22176229 -37.27346111
 -37.32015334 -37.4243151  -37.4539274  -37.52641301 -37.50012952
 -37.47201379 -37.44221742 -37.41096259 -37.43855504 -37.46290643
 -37.48423358 -37.54613445 -37.51630217 -37.48363125 -37.54268838
 -37.58853436 -37.62409671 -37.62462391 -37.59199366 -37.59022676
 -37.58658726 -37.58101697 -37.60715831 -37.59693147 -37.5471339
 -37.53186606 -37.46603144 -37.44492165 -37.35905392 -37.25651563
 -37.13575579 -36.99575631 -36.83629188 -36.94371863 -36.91695339
 -36.89166351 -36.72403338 -36.70798396 -36.52676888 -36.52786263
 -

[ 17.44516074  17.90304048  19.85890721  21.23960782  22.76635413
  23.57155435  25.43860314  26.51942769 -10.39342562 -10.42668275
 -10.31896067 -10.34753264 -10.37859688 -10.27779559 -10.30489806
 -10.21566191 -10.18700771 -10.21086283 -10.18274785 -10.21032532
 -10.13023301 -10.06095341 -10.08285806 -10.01668852 -10.0406592
 -10.02133538 -10.00332279  -9.98676006 -10.02697111 -10.0148588
  -9.94610323  -9.99765832 -10.06570199 -10.06535338  -9.98836715
 -10.07394476  -9.99529555 -10.09620434 -10.22311748 -10.13078414
 -10.15281027 -10.17831862 -10.34166752 -10.37822951 -10.41654293
 -10.62783852 -10.87110959 -10.91457248 -10.95333585 -10.98677395
 -11.01436993 -11.27023521 -11.04920645 -11.05616493 -11.05669043
 -10.85525916 -10.67944266 -10.84141139 -11.01520521 -10.81133333
 -10.79082359 -10.93825649 -11.09157492 -10.86830531 -10.99872969
 -11.13066485 -10.89636125 -10.70310796 -10.54358732 -10.61875526
 -10.69720265 -10.77750763 -10.6031334  -10.55833135 -10.51539995
 -10.3886294

tf.Tensor(
[-39.13413211 -39.13061937 -39.12495339 -39.11700815 -39.07025787
 -39.05807724 -39.08304581 -39.06468053 -38.99678725 -38.9138912
 -38.81399307 -38.69541785 -38.55708524 -38.5220246  -38.48601572
 -38.56611247 -38.63280906 -38.58895742 -38.64729413 -38.59737003
 -38.54394973 -38.5989658  -38.41855954 -38.20800424 -38.14452711
 -37.89682037 -37.62392615 -37.3319786  -37.57271079 -37.29925481
 -37.02226671 -37.35750187 -37.39959963 -37.69391713 -37.94254989
 -37.97381381 -38.01031135 -38.05135075 -38.25824151 -38.42773215
 -38.31366636 -38.34770445 -38.50865905 -38.53175979 -38.55468027
 -38.67826611 -38.59196669 -38.709228   -38.72065022 -38.81204448
 -38.81488762 -38.81630657 -38.73593828 -38.64853463 -38.65906603
 -38.56659932 -38.68463574 -38.69365528 -38.78665245 -38.70290213
 -38.61233414 -38.62512968 -38.53042896 -38.43198646 -38.33210417
 -38.50528194 -38.53780311 -38.4522359  -38.49560436 -38.53763816
 -38.57803225 -38.50609411 -38.55558213 -38.48984607 -38.42743411


[-10.36240275 -10.28816416  -9.93290166  -9.83879866  -9.73066432
  -9.8462357   -9.69500975  -9.53148023  -9.15976042  -9.17933528
  -9.18312983  -8.96493382  -8.5790031   -8.51767632  -8.15136521
  -8.05373018  -7.93999376  -7.68038605  -7.41739933  -7.15018625
  -6.96816704  -6.59725796  -6.3103111   -6.07803807  -5.70560137
  -5.38568519  -5.05157544  -4.74479902  -4.33346635  -3.91478138
  -3.54027982  -3.11033508  -2.65607158  -2.14892513  -1.61868055
  -1.10556216  -0.53689679   0.03770547   0.64332174   1.35309592
   2.10038721   2.88889356   3.72214774   4.54700619   5.44900936
   6.40260108   7.45278678   8.52081598   9.59029794  10.77075803
  11.92790866  13.32565587  14.70397017  16.15353544  17.67784189
  19.11036474  20.97434268  22.94768699  25.03736075  27.25069326
  29.39387515  31.39402949  33.43531899  35.53219356 -10.01848793
 -10.03172696 -10.04488792 -10.05755969 -10.00927286  -9.91595904
  -9.8387922   -9.80540098  -9.77293659  -9.74119316  -9.68087842
  -9.65126

tf.Tensor(
[-38.13446181 -38.65598662 -39.07960604 -39.03697325 -39.40816626
 -39.38475616 -39.69766877 -39.93780607 -39.91602025 -39.90500474
 -40.01526288 -40.01472712 -40.20636049 -40.20357395 -40.35037485
 -40.34440854 -40.61132162 -40.60540471 -40.59998385 -40.62611128
 -40.61930579 -40.66710512 -40.65717156 -40.69352106 -40.71975456
 -40.72289434 -40.70639085 -40.68762894 -40.70851764 -40.72330962
 -40.71693701 -40.72548445 -40.71332625 -40.7163005  -40.71540844
 -40.69135801 -40.68340375 -40.67034153 -40.65121098 -40.55986069
 -40.52289496 -40.47378055 -40.28632524 -40.01931277 -39.65116651
 -39.1630985  -38.78296296 -38.60245562 -38.39842959 -37.55837337
 -36.5895826  -35.53110923 -34.93823167 -34.37056938 -33.2828483
 -32.84321438 -31.85770496 -32.24456137 -32.66280842 -31.87175019
 -31.85335671 -32.5741459  -32.69398085 -32.26668099 -32.63924851
 -33.72063958 -34.18779335 -34.14180099 -34.22613656 -34.44084689
 -34.77967099 -35.22912197 -35.76814211 -36.368847   -36.99872822


[-9.20137730e+00 -9.15665811e+00 -9.11090618e+00 -9.06408901e+00
 -9.01624768e+00 -8.98386755e+00 -8.91694516e+00 -8.88570402e+00
 -8.81544604e+00 -8.76568830e+00 -8.71743513e+00 -8.70153947e+00
 -8.66170682e+00 -8.58824486e+00 -8.60379542e+00 -8.64725628e+00
 -8.64731153e+00 -8.66125600e+00 -8.79397211e+00 -8.97821191e+00
 -9.05618917e+00 -9.32745147e+00 -9.43932334e+00 -9.35235769e+00
 -9.27541240e+00 -9.63861486e+00 -9.79042718e+00 -9.68853695e+00
 -9.59635624e+00 -1.00350712e+01 -9.91621440e+00 -1.00867275e+01
 -1.05760807e+01 -1.03951630e+01 -1.08854559e+01 -1.10004385e+01
 -1.10895038e+01 -1.15347620e+01 -1.19458470e+01 -1.18750907e+01
 -1.21793478e+01 -1.24127752e+01 -1.25645095e+01 -1.21973320e+01
 -1.22028975e+01 -1.17436282e+01 -1.16299444e+01 -1.14532992e+01
 -1.09290070e+01 -1.07026945e+01 -1.02321054e+01 -1.00026315e+01
 -9.61602161e+00 -9.29350281e+00 -9.11143317e+00 -8.85662837e+00
 -8.63914882e+00 -8.44819636e+00 -8.27506601e+00 -8.13750673e+00
 -7.99575614e+00 -7.83098

[ -8.59731381  -8.64631328  -8.71635103  -8.61446328  -8.60962427
  -8.72001411  -8.85566092  -8.86249116  -8.86973692  -9.04205999
  -9.03817404  -9.22056775  -9.40164654  -9.12602482  -8.87084304
  -8.6330657   -8.75749206  -8.6751521   -8.5787204   -8.46752114
  -8.16252567  -7.87508321  -7.91260196  -7.75984518  -7.76710668
  -7.56437353  -7.17870807  -6.95886884  -6.72209599  -6.4679852
  -6.06205641  -5.78670462  -5.37707626  -5.19127846  -4.74749287
  -4.40640919  -4.15369185  -3.65038691  -3.14503491  -2.63217672
  -2.1071137   -1.63955804  -1.06828709  -0.4755363    0.07151064
   0.64809989   1.16558496   1.70274979   2.38798156   2.98716158
   3.90011356   4.84967308   5.58958076   6.65840038   7.64460954
   8.69351855   9.6529752   10.85102354  12.13045769  13.31209967
  14.78659098  16.36375832  18.04995535  19.65128403  21.38218049
  23.68813706  26.08356301  28.58208391  30.8991636   33.70045624
  36.63687901  39.72392924 -10.30252529 -10.39148313 -10.27453546
 -10.576225

tf.Tensor(
[-39.83457997 -39.75982892 -39.94841192 -40.11196497 -39.8035623
 -39.78012494 -39.52239931 -39.58756741 -39.67701513 -39.7881004
 -39.66992031 -39.61084227 -39.6150032  -39.68243243 -40.04916484
 -40.57967697 -40.83625998 -41.06674513 -41.38182488 -41.61544374
 -41.6436254  -41.81989615 -41.89717426 -42.00821946 -40.17605537
 -40.0577681  -40.17479516 -40.06036184 -39.72020206 -39.67011161
 -39.3759942  -39.68296    -39.44456714 -39.26013513 -39.14155299
 -39.39069837 -39.90150936 -40.1108082  -40.32169493 -40.52933787
 -40.5540172  -40.94215082 -41.11677086 -41.27644912 -41.42047522
 -41.63370671 -41.64974396 -41.6767734  -41.78286881 -41.92712565
 -42.03171661 -42.073807   -42.13993941 -42.13510765 -42.16065379
 -42.20520499 -42.2375129  -42.24376314 -42.24794161 -42.26650674
 -42.279225   -42.28719894 -42.26251744 -42.23379202 -42.20077864
 -42.18812901 -42.17254962 -42.17930506 -42.12639717 -42.06472822
 -41.99423847 -42.00801925 -41.96992582 -41.92642163 -41.81935703
 

In [ ]:
def discount_cumsum(x, discount):
    """
    magic from rllab for computing discounted cumulative sums of vectors.
    input: 
        vector x, 
        [x0, 
         x1, 
         x2]
    output:
        [x0 + discount * x1 + discount^2 * x2,  
         x1 + discount * x2,
         x2]
    """
    return scipy.signal.lfilter([1], [1, float(-discount)], x[::-1], axis=0)[::-1]

In [ ]:
rollout = generator_ppo.__next__()

In [ ]:
gae, td = get_gaeadv_vtarg(rollout, 0.95, 0.99)

In [ ]:
rews, vals = rollout["rew"][:198], rollout["vpred"][:198]
rews = np.append(rews, rollout["vpred"])
vals = np.append(vals, rollout["next_vpred"])
deltas = rews[:-1] + 0.99 * vals[1:] - vals[:-1]
gae2 = discount_cumsum(deltas, 0.99*0.95)

In [ ]:
np.sum(gae2 - gae)

In [ ]:
gae2

In [ ]:
gae

In [ ]:
gae-gae2

In [ ]:
rollout["new"][:198]

In [ ]:
act_dim

In [47]:
jen_vpg.actor_step

In [71]:
env.action_space.sample()

1